// The image upload boundary.
//
// The sniffing half is where a bad file is supposed to stop, so most of what is
// below is about things that must NOT be accepted — an SVG above all, because an
// accepted one is stored XSS on every page that renders it.
//
// The processImage tests need sharp but no database, no environment and no
// fixture files: the inputs are generated by sharp itself, so they are
// deterministic and CI needs nothing it does not already have. They are here
// because the properties they pin — that the output is re-encoded, that EXIF is
// gone, that a sideways photo is stood up — are the ones a reviewer cannot
// verify by reading.
import { describe, expect, it } from 'vitest'
import sharp from 'sharp'
import {
  ACCEPTED_TYPES,
  checkUpload,
  MAX_IMAGE_BYTES,
  sniffImageType,
  UPLOAD_REFUSAL_MESSAGES,
} from '../src/images/policy'
import { BIKE_PHOTO_BOX, PROCESSED_EXT, processImage } from '../src/images/process'

const bytes = (...b: number[]) => Uint8Array.from(b)
const JPEG = bytes(0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10)
const PNG = bytes(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00)

describe('sniffImageType', () => {
  it('knows the two formats it accepts', () => {
    expect(sniffImageType(JPEG)).toBe('jpeg')
    expect(sniffImageType(PNG)).toBe('png')
    expect(ACCEPTED_TYPES).toEqual(['jpeg', 'png'])
  })

  // THE ONE THAT MATTERS. An SVG is a document that can carry script, and one
  // served back from this app's own origin is stored XSS. It is refused by
  // construction — it is text and matches no magic number — and this test is
  // what stops someone "helpfully" adding it to the accepted list later.
  it('refuses an SVG, however it is dressed up', () => {
    for (const svg of ['<svg xmlns="http://www.w3.org/2000/svg"/>', '<?xml version="1.0"?><svg/>', '  <svg />']) {
      expect(sniffImageType(new TextEncoder().encode(svg)), svg).toBeNull()
    }
  })

  it('refuses other real image formats, which are not the same as unsafe', () => {
    expect(sniffImageType(bytes(0x47, 0x49, 0x46, 0x38, 0x39, 0x61))).toBeNull() // GIF89a
    expect(sniffImageType(bytes(0x52, 0x49, 0x46, 0x46, 0, 0, 0, 0, 0x57, 0x45, 0x42, 0x50))).toBeNull() // WEBP
    expect(sniffImageType(bytes(0x25, 0x50, 0x44, 0x46))).toBeNull() // %PDF
  })

  it('refuses HTML wearing a png name', () => {
    expect(sniffImageType(new TextEncoder().encode('<!doctype html><script>alert(1)</script>'))).toBeNull()
  })

  it('is not fooled by a magic number that appears later in the file', () => {
    expect(sniffImageType(bytes(0x00, 0xff, 0xd8, 0xff))).toBeNull()
  })

  it('handles a buffer shorter than the signature it is testing', () => {
    expect(sniffImageType(bytes(0x89, 0x50))).toBeNull()
    expect(sniffImageType(bytes())).toBeNull()
  })
})

describe('checkUpload', () => {
  it('accepts what it should', () => {
    expect(checkUpload(JPEG)).toEqual({ ok: true, type: 'jpeg' })
  })

  it('refuses an empty upload distinctly from an unreadable one', () => {
    expect(checkUpload(bytes())).toEqual({ ok: false, reason: 'empty' })
  })

  // Order is the point: an oversized file must be refused on its length, before
  // anything reads into it and long before anything decodes it.
  it('refuses an oversized file even when it is a real JPEG', () => {
    const big = new Uint8Array(MAX_IMAGE_BYTES + 1)
    big.set(JPEG, 0)
    expect(checkUpload(big)).toEqual({ ok: false, reason: 'too-large' })
  })

  it('has a message for every refusal it can return', () => {
    for (const reason of ['empty', 'too-large', 'unsupported'] as const) {
      expect(UPLOAD_REFUSAL_MESSAGES[reason], reason).toBeTruthy()
    }
  })
})

describe('processImage', () => {
  const solid = (width: number, height: number) =>
    sharp({ create: { width, height, channels: 3, background: { r: 200, g: 90, b: 20 } } })

  it('re-encodes to one format whatever came in', async () => {
    const png = await solid(400, 300).png().toBuffer()
    const out = await processImage(png, BIKE_PHOTO_BOX)
    expect(sniffImageType(out.data)).toBeNull() // no longer a PNG or a JPEG
    expect(
      await sharp(out.data)
        .metadata()
        .then((m) => m.format),
    ).toBe(PROCESSED_EXT)
  })

  it('shrinks a large photo to fit the box and keeps its shape', async () => {
    const jpeg = await solid(4000, 3000).jpeg().toBuffer()
    const out = await processImage(jpeg, BIKE_PHOTO_BOX)
    expect(out.width).toBeLessThanOrEqual(BIKE_PHOTO_BOX.width)
    expect(out.height).toBeLessThanOrEqual(BIKE_PHOTO_BOX.height)
    expect(out.width / out.height).toBeCloseTo(4 / 3, 2)
  })

  it('leaves a small photo at its own size rather than upscaling it', async () => {
    const png = await solid(320, 240).png().toBuffer()
    const out = await processImage(png, BIKE_PHOTO_BOX)
    expect([out.width, out.height]).toEqual([320, 240])
  })

  // A phone attaches GPS coordinates to a photo. An app that stores them and
  // serves the file publishes where the picture was taken.
  it('strips EXIF, including the GPS a phone attaches', async () => {
    const withExif = await solid(400, 300)
      .withExif({ IFD0: { Copyright: 'test' }, IFD2: { GPSLatitudeRef: 'N' } })
      .jpeg()
      .toBuffer()
    expect(
      await sharp(withExif)
        .metadata()
        .then((m) => m.exif),
    ).toBeTruthy()

    const out = await processImage(withExif, BIKE_PHOTO_BOX)
    expect(
      await sharp(out.data)
        .metadata()
        .then((m) => m.exif),
    ).toBeUndefined()
  })

  // The reason .rotate() comes first. A phone writes the pixels in sensor order
  // and an EXIF tag saying which way up they go; sharp writes no metadata to the
  // output, so without the rotate the tag would be dropped while the pixels
  // stayed on their side — a photo stored permanently sideways.
  it('stands a sideways photo up before the orientation tag is dropped', async () => {
    // withMetadata({orientation}), NOT withExif({IFD0:{Orientation}}). sharp
    // treats orientation as its own output option rather than a passthrough EXIF
    // tag — the withExif spelling writes a tag sharp then reads back as 1, so a
    // fixture built that way is not sideways at all and the test passes for the
    // wrong reason. Confirmed by reading metadata().orientation off both.
    const sideways = await solid(400, 300).withMetadata({ orientation: 6 }).jpeg().toBuffer()
    expect(
      await sharp(sideways)
        .metadata()
        .then((m) => m.orientation),
    ).toBe(6)

    const out = await processImage(sideways, BIKE_PHOTO_BOX)
    expect([out.width, out.height]).toEqual([300, 400])
  })

  it('fingerprints the output, so a changed picture is a changed URL', async () => {
    const a = await processImage(await solid(400, 300).png().toBuffer(), BIKE_PHOTO_BOX)
    const b = await processImage(await solid(400, 300).png().toBuffer(), BIKE_PHOTO_BOX)
    const c = await processImage(await solid(401, 300).png().toBuffer(), BIKE_PHOTO_BOX)
    expect(a.hash).toHaveLength(32)
    expect(a.hash).toBe(b.hash)
    expect(a.hash).not.toBe(c.hash)
  })
})
